const Ago23 = [
  {
    name: "Bautista Ventura Liliana Soledad",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61242967139",
  },
  {
    name: "Bautista Ventura Liliana Soledad",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Calhuante Nanci H",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "6893",
  },
  {
    name: "Calhuante Nanci H",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "61649192761",
  },
  {
    name: "D'Alessandro Paula Alejandra",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "D'Alessandro Paula Alejandra",
    concept: "Agosto",
    amount: 10500,
    payday: "",
    receipt: "153866",
  },
  {
    name: "Diaz Bianca",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "625127",
  },
  {
    name: "Fernandez Luciana Soledad",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "854748",
  },
  {
    name: "Fernandez Luciana Soledad",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "394915",
  },
  {
    name: "Guardia Sofia Valentina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61506095367",
  },
  {
    name: "Guardia Sofia Valentina",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "61506095367",
  },
  {
    name: "Ibarra Carmen Natalia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Ibarra Carmen Natalia",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "795395",
  },
  {
    name: "Ibarra Carmen Natalia",
    concept: "Septiembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Mansilla Dora María Belén",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "59960799105",
  },
  {
    name: "Mansilla Dora María Belén",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Muñoz Flavia Romina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "60287363194",
  },
  {
    name: "Muñoz Flavia Romina",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "230802",
  },
  {
    name: "Muñoz Flavia Romina",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "62885074001",
  },
  {
    name: "Ruidiaz Ana Beatriz",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "399467",
  },
  {
    name: "Ruidiaz Ana Beatriz",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Stork Ivana",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "10984797023230710",
  },
  {
    name: "Stork Ivana",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Vilanova Gabriela Edith",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "60646055550",
  },
  {
    name: "Vilanova Gabriela Edith",
    concept: "Agosto",
    amount: 2000,
    payday: "",
    receipt: "",
  },
  {
    name: "Zarate Natalia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "60659036720",
  },

  {
    name: "Acuña Nicolas Antonio",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "8979",
  },
  {
    name: "Acuña Nicolas Antonio",
    concept: "Agosto",
    amount: 5000,
    payday: "",
    receipt: "8979",
  },
  {
    name: "Alvarez Brisa Morena",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61232390279",
  },
  {
    name: "Alvarez Brisa Morena",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62039420418",
  },
  {
    name: "Andres Maria Gabriela",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "3919",
  },
  {
    name: "Andres Maria Gabriela",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "111",
  },
  {
    name: "Aranciaga Lara",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61986424086",
  },
  {
    name: "Aranciaga Lara",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Arola Verónica Gisela",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Arola Verónica Gisela",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Capriccio Analía Patricia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "295431",
  },
  {
    name: "Capriccio Analía Patricia",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Capriccio Analía Patricia",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "842654",
  },
  {
    name: "Cuevas Patricia Norma",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61055569231",
  },
  {
    name: "Cuevas Patricia Norma",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "1101",
  },
  {
    name: "Cuevas Patricia Norma",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "63010992645",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Ferrari Maria José De Los Ángeles",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "709324",
  },
  {
    name: "Ferrari Maria José De Los Ángeles",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "710263",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Galarza Cristina Alejandra",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "30027692530",
  },
  {
    name: "Galarza Cristina Alejandra",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "788149",
  },
  {
    name: "Galarza Cristina Alejandra",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "1603977",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Mardones Raquel Elizabeth",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Mardones Raquel Elizabeth",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Moyano Silvana Natalia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "230728",
  },
  {
    name: "Moyano Silvana Natalia",
    concept: "Agosto",
    amount: 10500,
    payday: "",
    receipt: "50087749022230810",
  },
  {
    name: "Jimenez Mercedes Cecilia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Jimenez Mercedes Cecilia",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Leiva Germán Alberto",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61835361204",
  },
  {
    name: "Leiva Germán Alberto",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "61981506851",
  },
  {
    name: "López, Juan Ezequiel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61232324497",
  },
  {
    name: "López, Juan Ezequiel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "6199348403",
  },
  {
    name: "Pintos Agustina Ailen",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "78798",
  },
  {
    name: "Pintos Agustina Ailen",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62364258682",
  },
  {
    name: "Rodríguez Romina Isabel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "435585",
  },
  {
    name: "Rodríguez Romina Isabel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "435585",
  },
  {
    name: "Romero Maria Soledad",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61155368157",
  },
  {
    name: "Romero Maria Soledad",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "133090",
  },
  {
    name: "Salinas Medina Silvia Elizabeth",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62078935434",
  },
  {
    name: "Salinas Medina Silvia Elizabeth",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62078935434",
  },
  {
    name: "Sosa Araceli Evelin",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "60166593966",
  },
  {
    name: "Torres Laura Karina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "97203",
  },
  {
    name: "Torres Laura Karina",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "97203",
  },
  {
    name: "Turco Romina Luján",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62070824368",
  },
  {
    name: "Turco Romina Luján",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Vega María Alcira",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "705994",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61866029394",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Acuña Nicolas Antonio",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "8979",
  },
  {
    name: "Acuña Nicolas Antonio",
    concept: "Agosto",
    amount: 5000,
    payday: "",
    receipt: "8979",
  },
  {
    name: "Alvarez Brisa Morena",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61232390279",
  },
  {
    name: "Alvarez Brisa Morena",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62039420418",
  },
  {
    name: "Andres Maria Gabriela",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "3919",
  },
  {
    name: "Andres Maria Gabriela",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "111",
  },
  {
    name: "Aranciaga Lara",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61986424086",
  },
  {
    name: "Aranciaga Lara",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Arola Verónica Gisela",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Arola Verónica Gisela",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Capriccio Analía Patricia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "295431",
  },
  {
    name: "Capriccio Analía Patricia",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Capriccio Analía Patricia",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "842654",
  },
  {
    name: "Cuevas Patricia Norma",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61055569231",
  },
  {
    name: "Cuevas Patricia Norma",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "1101",
  },
  {
    name: "Cuevas Patricia Norma",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "63010992645",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Di Donato Silvina María Elda",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "172633",
  },
  {
    name: "Ferrari Maria José De Los Ángeles",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "709324",
  },
  {
    name: "Ferrari Maria José De Los Ángeles",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "710263",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Figueredo Clara Irene",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "7724",
  },
  {
    name: "Galarza Cristina Alejandra",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "30027692530",
  },
  {
    name: "Galarza Cristina Alejandra",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "788149",
  },
  {
    name: "Galarza Cristina Alejandra",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "1603977",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Giménez Elisa Beatriz",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Gonzo Aneli Beatriz",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "347472",
  },
  {
    name: "Mardones Raquel Elizabeth",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Mardones Raquel Elizabeth",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Moyano Silvana Natalia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "230728",
  },
  {
    name: "Moyano Silvana Natalia",
    concept: "Agosto",
    amount: 10500,
    payday: "",
    receipt: "50087749022230810",
  },
  {
    name: "Jimenez Mercedes Cecilia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Jimenez Mercedes Cecilia",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Leiva Germán Alberto",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61835361204",
  },
  {
    name: "Leiva Germán Alberto",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "61981506851",
  },
  {
    name: "López, Juan Ezequiel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61232324497",
  },
  {
    name: "López, Juan Ezequiel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "6199348403",
  },
  {
    name: "Pintos Agustina Ailen",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "78798",
  },
  {
    name: "Pintos Agustina Ailen",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62364258682",
  },
  {
    name: "Rodríguez Romina Isabel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "435585",
  },
  {
    name: "Rodríguez Romina Isabel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "435585",
  },
  {
    name: "Romero Maria Soledad",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61155368157",
  },
  {
    name: "Romero Maria Soledad",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "133090",
  },
  {
    name: "Salinas Medina Silvia Elizabeth",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62078935434",
  },
  {
    name: "Salinas Medina Silvia Elizabeth",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62078935434",
  },
  {
    name: "Sosa Araceli Evelin",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "60166593966",
  },
  {
    name: "Torres Laura Karina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "97203",
  },
  {
    name: "Torres Laura Karina",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "97203",
  },
  {
    name: "Turco Romina Luján",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62070824368",
  },
  {
    name: "Turco Romina Luján",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Vega María Alcira",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "705994",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61866029394",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Agosto",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Septiembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Octubre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Noviembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Yucra Luis Miguel",
    concept: "Diciembre",
    amount: 7000,
    payday: "",
    receipt: "",
  },
  {
    name: "Abeiro Liliana Edith",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62013512230",
  },
  {
    name: "Abeiro Liliana Edith",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Abeiro Liliana Edith",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "62887014995",
  },
  {
    name: "Avila Adriana",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "79021230713",
  },
  {
    name: "Avila Adriana",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Avila Adriana",
    concept: "Septiembre",
    amount: 3000,
    payday: "",
    receipt: "61928699719",
  },
  {
    name: "Escobar Gloria Mabel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "11221403016230808",
  },
  {
    name: "Escobar Gloria Mabel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Eyheramonho Araque Josabet",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "5521",
  },
  {
    name: "Eyheramonho Araque Josabet",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Fuente Bonafede Alejandra Paola",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61567604331",
  },
  {
    name: "Garcia Fava Maria Victoria",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "19008347",
  },
  {
    name: "Garcia Fava Maria Victoria",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "19008347",
  },
  {
    name: "Guaimas Andrea Lorena",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Guaimas Andrea Lorena",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "",
  },
  {
    name: "Guerrero Jessica Romina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "300943",
  },
  {
    name: "Guerrero Jessica Romina",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "597564",
  },
  {
    name: "Guerrero Jessica Romina",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "62949546289",
  },
  {
    name: "Herrera Mariana Beatriz",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Herrera Mariana Beatriz",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "",
  },
  {
    name: "Maicher Francesca",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "145241",
  },
  {
    name: "Maicher Francesca ",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "145241",
  },
  {
    name: "Maicher Francesca ",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "145241",
  },
  {
    name: "Mansilla Emilce Vanesa",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61815150007",
  },
  {
    name: "Mansilla Emilce Vanesa",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "61815150007",
  },
  {
    name: "Medina Rut Noemí",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "60395246112",
  },
  {
    name: "Medina Rut Noemí",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Medina Rut Noemí",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Medina Rut Noemí",
    concept: "Octubre",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Medina Rut Noemí",
    concept: "Noviembre",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Medina Rut Noemí",
    concept: "Diciembre",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Pino Camila Antonella",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61681077426",
  },
  {
    name: "Pino Camila Antonella",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Pino Camila Antonella",
    concept: "Septiembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Pino Camila Antonella",
    concept: "Octubre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Pino Camila Antonella",
    concept: "Noviembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Pino Camila Antonella",
    concept: "Diciembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Poggio Sayago Maia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Poggio Sayago Maia",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Ramirez Alicia De La Cruz",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Ramirez Alicia De La Cruz",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Recabarren Patricia Sulman",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "579325",
  },
  {
    name: "Recabarren Patricia Sulman",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "579325",
  },
  {
    name: "Rolon Lorena Carolina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61927894303",
  },
  {
    name: "Rolon Lorena Carolina",
    concept: "Agosto",
    amount: 4000,
    payday: "",
    receipt: "",
  },
  {
    name: "Sape Jonathan",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62054436656",
  },
  {
    name: "Sape Jonathan",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "62054436656",
  },
  {
    name: "Sape Jonathan",
    concept: "Septiembre",
    amount: 9000,
    payday: "",
    receipt: "62876711793",
  },
  {
    name: "Sape Jonathan",
    concept: "Octubre",
    amount: 9000,
    payday: "",
    receipt: "",
  },
  {
    name: "Sape Jonathan",
    concept: "Noviembre",
    amount: 9000,
    payday: "",
    receipt: "",
  },
  {
    name: "Sape Jonathan",
    concept: "Diciembre",
    amount: 9000,
    payday: "",
    receipt: "",
  },
  {
    name: "Sere Veronica Jorgelina ",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62148646645",
  },
  {
    name: "Sere Veronica Jorgelina ",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Sere Veronica Jorgelina ",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Allegretti Monica Sandra",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Allegretti Monica Sandra",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "",
  },
  {
    name: "Allegretti Monica Sandra",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Alomar Liliana Evangelina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Alomar Liliana Evangelina",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62179487356",
  },
  {
    name: "Babuini Abigail Carmina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "60916714295",
  },
  {
    name: "Babuini Abigail Carmina",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Barrera Fernanda Ayelen",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "8473",
  },
  {
    name: "Barrera Fernanda Ayelen",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Belén Silvina Elizabeth",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "57602",
  },
  {
    name: "Biasotti Arangio Paula Lourdes",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "9743",
  },
  {
    name: "Biasotti Arangio Paula Lourdes",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "9743",
  },
  {
    name: "Boccarelli Analia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "671404",
  },
  {
    name: "Boccarelli Analia",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "935760",
  },
  {
    name: "Cajal Alejandra Paola",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Cajal Alejandra Paola",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "663274",
  },
  {
    name: "Celiz Gilda Lorena",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "734946056",
  },
  {
    name: "Celiz Gilda Lorena",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Colella Daniela Fernanda",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "60934479929",
  },
  {
    name: "Colella Daniela Fernanda",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Colella Daniela Fernanda",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "62876282623",
  },
  {
    name: "Fernández Belinda Mabel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "516862",
  },
  {
    name: "Fernández Belinda Mabel",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "516862",
  },
  {
    name: "Fernández Belinda Mabel",
    concept: "Septiembre",
    amount: 8000,
    payday: "",
    receipt: "516862",
  },
  {
    name: "Fernández Belinda Mabel",
    concept: "Octubre",
    amount: 8000,
    payday: "",
    receipt: "516862",
  },
  {
    name: "Fernández Belinda Mabel",
    concept: "Noviembre",
    amount: 8000,
    payday: "",
    receipt: "516862",
  },
  {
    name: "Fernández Belinda Mabel",
    concept: "Diciembre",
    amount: 8000,
    payday: "",
    receipt: "516862",
  },
  {
    name: "Garrone Fernando Marcos",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "3144",
  },
  {
    name: "Garrone Fernando Marcos",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "3144",
  },
  {
    name: "Gutierrez Monica Gabriela",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61589785407",
  },
  {
    name: "Gutierrez Monica Gabriela",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Jara Provoste María Noelia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Jara Provoste María Noelia",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Kresich Erica Vanesa",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62180010070",
  },
  {
    name: "Kresich Erica Vanesa",
    concept: "Agosto",
    amount: 5000,
    payday: "",
    receipt: "62180010070",
  },
  {
    name: "Melgarejo Ana Belen",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "22842",
  },
  {
    name: "Melgarejo Ana Belen",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "6827",
  },
  {
    name: "Perales Leticia de los Angeles",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "208754",
  },
  {
    name: "Perales Leticia de los Angeles",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "208754",
  },
  {
    name: "Rivero Zulma Esther",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Rivero Zulma Esther",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Rivero Zulma Esther",
    concept: "Septiembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Rivero Zulma Esther",
    concept: "Octubre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Rivero Zulma Esther",
    concept: "Noviembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Rivero Zulma Esther",
    concept: "Diciembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Salas Pablo Gabriel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62429503083",
  },
  {
    name: "Salas Pablo Gabriel",
    concept: "Agosto",
    amount: 9500,
    payday: "",
    receipt: "62429503083",
  },
  {
    name: "Szlago Marina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Szlago Marina",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Szlago Marina",
    concept: "Septiembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Szlago Marina",
    concept: "Octubre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Szlago Marina",
    concept: "Noviembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Szlago Marina",
    concept: "Diciembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "Taborda Elena Belen",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62185917228",
  },
  {
    name: "Taborda Elena Belen",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62185917228",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Septiembre",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Octubre",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Noviembre",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Diciembre",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Tovagliari Andrea Elizabeth",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "927038",
  },
  {
    name: "Tovagliari Andrea Elizabeth",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "927038",
  },
  {
    name: "Belavlovsky Roxana",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "22868",
  },
  {
    name: "Belavlovsky Roxana",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "3214598",
  },
  {
    name: "Belavlovsky Roxana",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "12921636",
  },
  {
    name: "Dicosimo Mirta Graciela",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "60355605787",
  },
  {
    name: "Dicosimo Mirta Graciela",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "661447129",
  },
  {
    name: "Di Sascio Gabriela",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Di Sascio Gabriela",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "",
  },
  {
    name: "Fernandez Adelaida Beatriz",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61671678816",
  },
  {
    name: "Fernandez Adelaida Beatriz",
    concept: "Agosto",
    amount: 7500,
    payday: "",
    receipt: "",
  },
  {
    name: "Garay Bianchi Abigail",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "79123",
  },
  {
    name: "Garay Bianchi Abigail",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "4049390",
  },
  {
    name: "Goffredo Silvia Patricia ",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "244039",
  },
  {
    name: "Goffredo Silvia Patricia ",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "273761",
  },
  {
    name: "Iramain Ledesma Deborah Pamela",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "50213888015230830",
  },
  {
    name: "Iramain Ledesma Deborah Pamela",
    concept: "Agosto",
    amount: 9500,
    payday: "",
    receipt: "50213888015230830",
  },
  {
    name: "Rios Miriam Isabel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62059942403",
  },
  {
    name: "Rios Miriam Isabel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62111375217",
  },
  {
    name: "Sequeira Victoria Alejandra",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62217652874",
  },
  {
    name: "Sequeira Victoria Alejandra",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62217652874",
  },
  {
    name: "Solari Maria Gimena",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "100363",
  },
  {
    name: "Solari Maria Gimena",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "323178",
  },
  {
    name: "Ventuala Gladys Ester",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61887214608",
  },
  {
    name: "Ventuala Gladys Ester",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62249515868",
  },
  {
    name: "Garay Bianchi Abigail",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "79123",
  },
  {
    name: "Garay Bianchi Abigail",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "4049390",
  },
  {
    name: "Garcia Lorna ",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "426122",
  },
  {
    name: "Garcia Lorna ",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "426122",
  },
  {
    name: "Moyano Francisco Abel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61635597258",
  },
  {
    name: "Moyano Francisco Abel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62058344911",
  },
  {
    name: "Oviedo Cecilia Carolina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "915606",
  },
  {
    name: "Oviedo Cecilia Carolina",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "898326",
  },
  {
    name: "Parras Luciana",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "756499",
  },
  {
    name: "Parras Luciana",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "",
  },
  {
    name: "Páez Agustina Ayelén",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61843587659",
  },
  {
    name: "Páez Agustina Ayelén",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62183660350",
  },
  {
    name: "Rodriguez Estefanía Marlene",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61862030565",
  },
  {
    name: "Rodriguez Estefanía Marlene",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "61862030565",
  },
  {
    name: "Rossi Carrasco Agustina Belén",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "90579484",
  },
  {
    name: "Rossi Carrasco Agustina Belén",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "97520676",
  },
  {
    name: "Cardoza Oliva Luisa Angelica",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62186504824",
  },
  {
    name: "Cardoza Oliva Luisa Angelica",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62186504824",
  },
];

const quedaronSinHacer = [
  {
    name: "D'Alessandro Paula Alejandra",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "D'Alessandro Paula Alejandra",
    concept: "Agosto",
    amount: 10500,
    payday: "",
    receipt: "153866",
  },
  {
    name: "Fernandez Luciana Soledad",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "854748",
  },
  {
    name: "Fernandez Luciana Soledad",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "394915",
  },
  {
    name: "Ibarra Carmen Natalia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Ibarra Carmen Natalia",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "795395",
  },
  {
    name: "Ibarra Carmen Natalia",
    concept: "Septiembre",
    amount: 8000,
    payday: "",
    receipt: "",
  },
  {
    name: "López, Juan Ezequiel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61232324497",
  },
  {
    name: "López, Juan Ezequiel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "6199348403",
  },
  {
    name: "Rodríguez Romina Isabel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "435585",
  },
  {
    name: "Rodríguez Romina Isabel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "435585",
  },
  {
    name: "López, Juan Ezequiel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "61232324497",
  },
  {
    name: "López, Juan Ezequiel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "6199348403",
  },
  {
    name: "Rodríguez Romina Isabel",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "435585",
  },
  {
    name: "Rodríguez Romina Isabel",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "435585",
  },
  {
    name: "Avila Adriana",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "79021230713",
  },
  {
    name: "Avila Adriana",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Avila Adriana",
    concept: "Septiembre",
    amount: 3000,
    payday: "",
    receipt: "61928699719",
  },
  {
    name: "Herrera Mariana Beatriz",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "",
  },
  {
    name: "Herrera Mariana Beatriz",
    concept: "Agosto",
    amount: 9000,
    payday: "",
    receipt: "",
  },
  {
    name: "Maicher Francesca",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "145241",
  },
  {
    name: "Maicher Francesca",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "145241",
  },
  {
    name: "Maicher Francesca",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "145241",
  },
  {
    name: "Sere Veronica Jorgelina",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62148646645",
  },
  {
    name: "Sere Veronica Jorgelina",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  {
    name: "Sere Veronica Jorgelina",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "",
  },
  ,
  {
    name: "Belén Silvina Elizabeth",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "57602",
  },
  ,
  {
    name: "Perales Leticia de los Angeles",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "208754",
  },
  {
    name: "Perales Leticia de los Angeles",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "208754",
  },
  {
    name: "Taborda Elena Belen",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "62185917228",
  },
  {
    name: "Taborda Elena Belen",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "62185917228",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Agosto",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Septiembre",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Octubre",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Noviembre",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Terracol Carolina Ines",
    concept: "Diciembre",
    amount: 8000,
    payday: "",
    receipt: "678985",
  },
  {
    name: "Belavlovsky Roxana",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "22868",
  },
  {
    name: "Belavlovsky Roxana",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "3214598",
  },
  {
    name: "Belavlovsky Roxana",
    concept: "Septiembre",
    amount: 10000,
    payday: "",
    receipt: "12921636",
  },
  {
    name: "Goffredo Silvia Patricia",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "244039",
  },
  {
    name: "Goffredo Silvia Patricia",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "273761",
  },
  {
    name: "Garcia Lorna",
    concept: "Matrícula",
    amount: 5000,
    payday: "",
    receipt: "426122",
  },
  {
    name: "Garcia Lorna",
    concept: "Agosto",
    amount: 10000,
    payday: "",
    receipt: "426122",
  },
];





const valores = [
  {
    name: "Achinelli Marisa ",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 4500,
    julio: 5500,
  },
  {
    name: "Acuña Nicolas",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: null,
    julio: null,
  },
  {
    name: "Aguado Tiziana",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Alvarez Brisa",
    matrícula: 4500,
    marzo: 3000,
    abril: 3000,
    mayo: 3000,
    junio: 5500,
    julio: 4000,
  },
  {
    name: "Andrade Sonia Analía ",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 6000,
    julio: 4000,
  },
  {
    name: "Andres Maria Gabriela",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Arguello Mariana",
    matrícula: 4500,
    marzo: 5000,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Arola Verónica Gisela",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Balmaceda Victoria ",
    matrícula: 4500,
    marzo: 5000,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Bonhoure Nicole ",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Capriccio Analía",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Caragunis Maria Gimena",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: null,
    julio: null,
  },
  {
    name: "Condori Carla Mariel",
    matrícula: 1500,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Disser Milagros ",
    matrícula: "RECURSA",
    marzo: "RECURSA",
    abril: "RECURSA",
    mayo: "RECURSA",
    junio: "RECURSA",
    julio: "RECURSA",
  },
  {
    name: "Espindola Florencia Araceli",
    matrícula: 1000,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Cuevas Patricia",
    matrícula: 3600,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Delgado Vanesa",
    matrícula: 4500,
    marzo: 5000,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Di Donato Silvina María Elda",
    matrícula: 2250,
    marzo: 5000,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Epinal Maria Laura",
    matrícula: 4500,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Escalante Melani",
    matrícula: 4500,
    marzo: 5000,
    abril: 5000,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Ferrari Florencia ",
    matrícula: 2250,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Figueredo Clara",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Frias Yesica Roxana",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Garcia Florencia",
    matrícula: 4500,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Garrote Ines",
    matrícula: 4500,
    marzo: 3825,
    abril: 3825,
    mayo: 3825,
    junio: 3825,
    julio: 3825,
  },
  {
    name: "Giménez Elisa Beatriz",
    matrícula: 3600,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Geringer Carolina",
    matrícula: 4500,
    marzo: 4500,
    abril: 5000,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Gonzalez Brisa Stephanie",
    matrícula: 3000,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Gonzo Aneli",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Hertel Antonela Maricel",
    matrícula: 4500,
    marzo: 5000,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Hood Jennifer ",
    matrícula: 3000,
    marzo: 4500,
    abril: 4500,
    mayo: 5000,
    junio: 5500,
    julio: 6000,
  },
  {
    name: "Jimenez De Navarro Mercedes",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Klubus Vanesa ",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 6000,
    julio: 6000,
  },
  {
    name: "Leiva German Alberto",
    matrícula: 4500,
    marzo: 3500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Lemos Lucía",
    matrícula: 4500,
    marzo: 4500,
    abril: 5000,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Losada Natalia Fernanda ",
    matrícula: "-",
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: null,
  },
  {
    name: "Lucero Fabiana ",
    matrícula: 4500,
    marzo: 5000,
    abril: 4000,
    mayo: 5500,
    junio: 5500,
    julio: null,
  },
  {
    name: "López, Juan Ezequiel ",
    matrícula: 4500,
    marzo: 5000,
    abril: 4500,
    mayo: 5000,
    junio: 6000,
    julio: 5000,
  },
  {
    name: "Machado Rosa Eduarda",
    matrícula: 4500,
    marzo: 4500,
    abril: 5000,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Mallo Santana Agustina Belen",
    matrícula: 2250,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Mallo Estefanía ",
    matrícula: 2250,
    marzo: 5000,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Mardones Raquel",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Margaria Lorena",
    matrícula: 3000,
    marzo: 5000,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "MELO NUÑEZ FABIOLA ",
    matrícula: 3000,
    marzo: 5000,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Miksa Paula Pilar",
    matrícula: 3000,
    marzo: 4000,
    abril: 4500,
    mayo: 5000,
    junio: 5000,
    julio: 5000,
  },
  {
    name: "Miranda Veronica Andrea",
    matrícula: 4500,
    marzo: 5000,
    abril: 4500,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Montenegro Mirta",
    matrícula: "-",
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Moyano Debora  ",
    matrícula: 3000,
    marzo: 4000,
    abril: 4500,
    mayo: 5000,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Moyano Maria Esther",
    matrícula: 4500,
    marzo: 4500,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Moyano Silvana",
    matrícula: 4500,
    marzo: 5000,
    abril: 4500,
    mayo: 5500,
    junio: 5500,
    julio: 6000,
  },
  {
    name: "Ponteprimo Ana Laura",
    matrícula: 4500,
    marzo: 4500,
    abril: 7000,
    mayo: 6000,
    junio: 6000,
    julio: 5500,
  },
  {
    name: "Pintos Agustina Ailén",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Pundan Joaquin",
    matrícula: 3000,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "QUIROZ Ester Noemi",
    matrícula: 4500,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Reyes Liliana",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: null,
  },
  {
    name: "Rios Garcia Mariana Zulma",
    matrícula: 4500,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Ripoll Yanina",
    matrícula: 4500,
    marzo: 5000,
    abril: 5000,
    mayo: 5500,
    junio: 5500,
    julio: 6000,
  },
  {
    name: "Rivero Mailen",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 5000,
    junio: null,
    julio: null,
  },
  {
    name: "Rodríguez Marcela",
    matrícula: 3000,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Rodríguez Romina Isabel ",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Romero Maria Soledad",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Salinas Medina Silvia Elizabeth",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Sosa Araceli Evelin",
    matrícula: 4500,
    marzo: 5000,
    abril: 4500,
    mayo: 5500,
    junio: 6500,
    julio: 5500,
  },
  {
    name: "Staltari Patricia ",
    matrícula: 4500,
    marzo: 5000,
    abril: 4500,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Suarez Silvia Beatriz",
    matrícula: 4500,
    marzo: 3600,
    abril: 3600,
    mayo: 4100,
    junio: 4600,
    julio: 4600,
  },
  {
    name: "Tejerina Liliana Del Valle ",
    matrícula: 4500,
    marzo: 5500,
    abril: 4500,
    mayo: 5500,
    junio: null,
    julio: null,
  },
  {
    name: "Tormo Monica Adriana",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Torres Laura Karina",
    matrícula: 3000,
    marzo: 5000,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Uribe Durand Priscila Tatiana ",
    matrícula: 3000,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Turco Romina Luján",
    matrícula: 4500,
    marzo: 5000,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Vargas Escalante Isaías Augusto",
    matrícula: 4500,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Vega María Alcira",
    matrícula: 4500,
    marzo: 4500,
    abril: 5500,
    mayo: 5500,
    junio: 6000,
    julio: 5500,
  },
  {
    name: "Velazquez Juan Antonio",
    matrícula: 3000,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Avalos Melanie Julieta",
    matrícula: 4500,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Yucra Luis Miguel",
    matrícula: 2250,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Zacarías Celeste",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 4500,
    junio: 5500,
    julio: 5500,
  },
  {
    name: "Balent Santiago Román",
    matrícula: 4500,
    marzo: null,
    abril: null,
    mayo: null,
    junio: null,
    julio: null,
  },
  {
    name: "Aranciaga Lara",
    matrícula: 4500,
    marzo: 4500,
    abril: 4500,
    mayo: 5000,
    junio: 6000,
    julio: 6000,
  },
];

const comprobantes = [
  {
    name: "Achinelli Marisa ",
    matrícula: null,
    fecha_matricula: "01/03",
    destino_matricula: "MP D",
    marzo: "",
    fecha_marzo: "07/03",
    destino_marzo: "MP D",
    abril: "-",
    fecha_abril: "10/04",
    destino_abril: "MP D",
    mayo: "Cuenta Dni",
    fecha_mayo: "02/05",
    destino_mayo: "MP D",
    junio: "Cuenta Dni",
    fecha_junio: "09/06",
    destino_junio: "MP D",
    julio: 508809103,
    fecha_julio: "16/07",
    destino_julio: "MP D",
  },
  {
    name: "Acuña Nicolas",
    matrícula: 2699,
    fecha_matricula: "1/3",
    destino_matricula: "Banco F",
    marzo: 2699,
    fecha_marzo: "1/3",
    destino_marzo: "Banco F",
    abril: 8186,
    fecha_abril: "11/04",
    destino_abril: "Banco D",
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Aguado Tiziana",
    matrícula: 55273610255,
    fecha_matricula: "2/3",
    destino_matricula: "MP D",
    marzo: 55273610255,
    fecha_marzo: "2/3",
    destino_marzo: "MP D",
    abril: 56395873826,
    fecha_abril: "01/04",
    destino_abril: "MP",
    mayo: 57636168638,
    fecha_mayo: "03/05",
    destino_mayo: "MP D",
    junio: 58786551829,
    fecha_junio: "02/06",
    destino_junio: "MP D",
    julio: 59979162795,
    fecha_julio: "30/06",
    destino_julio: "MP D",
  },
  {
    name: "Alvarez Brisa",
    matrícula: 55182895421,
    fecha_matricula: "28/02",
    destino_matricula: "MP D",
    marzo: 55614146186,
    fecha_marzo: "10/03",
    destino_marzo: "MP D",
    abril: 56587976941,
    fecha_abril: "06/04",
    destino_abril: "MP D",
    mayo: 57836847959,
    fecha_mayo: "09/05",
    destino_mayo: "MP D",
    junio: 59093413536,
    fecha_junio: "07/06",
    destino_junio: "MP D",
    julio: 60312199934,
    fecha_julio: "05/07",
    destino_julio: "MP D",
  },
  {
    name: "Andrade Sonia Analía ",
    matrícula: "53089194412 - 55175741273",
    fecha_matricula: "- / 28-02",
    destino_matricula: "MP",
    marzo: 55175741273,
    fecha_marzo: "28/02",
    destino_marzo: "MP",
    abril: 56340844046,
    fecha_abril: "30/03",
    destino_abril: "MP",
    mayo: 58009166055,
    fecha_mayo: "13/05",
    destino_mayo: "MP D",
    junio: 60107653872,
    fecha_junio: "01/07",
    destino_junio: "MP D",
    julio: "60107653872 - 60294595070",
    fecha_julio: "1/07/2023 - 05/07",
    destino_julio: "MP D",
  },
  {
    name: "Andres Maria Gabriela",
    matrícula: 1741,
    fecha_matricula: "1/3",
    destino_matricula: "Banco F",
    marzo: 8111,
    fecha_marzo: "04/03",
    destino_marzo: "Banco F",
    abril: 1814,
    fecha_abril: "08/04",
    destino_abril: "Banco F",
    mayo: 1947,
    fecha_mayo: "10/05",
    destino_mayo: "Banco D",
    junio: 3819,
    fecha_junio: "06/06",
    destino_junio: "Banco D",
    julio: 1523289,
    fecha_julio: "07/07",
    destino_julio: "MP D",
  },
  {
    name: "Arguello Mariana",
    matrícula: 54572012620,
    fecha_matricula: "13/02",
    destino_matricula: "MP F",
    marzo: 56305337906,
    fecha_marzo: "29/03",
    destino_marzo: "MP F",
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Arola Verónica Gisela",
    matrícula: 55886664132,
    fecha_matricula: "17/03",
    destino_matricula: "MP D",
    marzo: 55890756445,
    fecha_marzo: "18/03",
    destino_marzo: "MP D",
    abril: 56829817756,
    fecha_abril: "12/04",
    destino_abril: "MP D",
    mayo: 57591968009,
    fecha_mayo: "03/05",
    destino_mayo: "MP D",
    junio: 59142008238,
    fecha_junio: "08/06",
    destino_junio: "MP D",
    julio: "Cuenta Dni ",
    fecha_julio: "15/07",
    destino_julio: "MP",
  },
  {
    name: "Balmaceda Victoria ",
    matrícula: 55334133545,
    fecha_matricula: "04/03",
    destino_matricula: "MP D",
    marzo: 55895008826,
    fecha_marzo: "18/03",
    destino_marzo: "MP D",
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Bonhoure Nicole ",
    matrícula: "644494 - 54974506835",
    fecha_matricula: "- / 22-02",
    destino_matricula: "BCO SONIA - MP F",
    marzo: 55533383957,
    fecha_marzo: "09/03",
    destino_marzo: "MP ",
    abril: 56698887341,
    fecha_abril: "10/04",
    destino_abril: "MP D",
    mayo: 57737656674,
    fecha_mayo: "05/05",
    destino_mayo: "MP D",
    junio: 59278729533,
    fecha_junio: "13/06",
    destino_junio: "MP D",
    julio: 60367439271,
    fecha_julio: "08/07",
    destino_julio: "MP D",
  },
  {
    name: "Capriccio Analía",
    matrícula: "-",
    fecha_matricula: "2/3",
    destino_matricula: "MP D",
    marzo: "-",
    fecha_marzo: "2/3",
    destino_marzo: "MP D",
    abril: "-",
    fecha_abril: "03/04",
    destino_abril: "MP D",
    mayo: "RNEGJ468",
    fecha_mayo: "03/05",
    destino_mayo: "MP D",
    junio: "RNEGJ468 - WNE7RQ5X",
    fecha_junio: "3/05/2023 - 02/06",
    destino_junio: "MP D",
    julio: "Cuenta Dni",
    fecha_julio: "05/07",
    destino_julio: "MP D",
  },
  {
    name: "Caragunis Maria Gimena",
    matrícula: "252959555 - 55299450819",
    fecha_matricula: "- / 03-03",
    destino_matricula: "MP INST - MP F",
    marzo: 55299450819,
    fecha_marzo: "03-03",
    destino_marzo: "MP F",
    abril: 56473352644,
    fecha_abril: "03/04",
    destino_abril: "MP F",
    mayo: 57703710288,
    fecha_mayo: "04/05",
    destino_mayo: "MP D",
    junio: 59476945730,
    fecha_junio: "15/06",
    destino_junio: "MP D",
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Cuevas Patricia",
    matrícula: 1667566,
    fecha_matricula: "06/02/23",
    destino_matricula: "MP F",
    marzo: 55612916011,
    fecha_marzo: "11/03",
    destino_marzo: "MP D",
    abril: 56508001624,
    fecha_abril: "04/04",
    destino_abril: "MP D",
    mayo: 57714793466,
    fecha_mayo: "05/05",
    destino_mayo: "MP D",
    junio: 58858250682,
    fecha_junio: "02/06",
    destino_junio: "MP D",
    julio: 60132928265,
    fecha_julio: "04/07",
    destino_julio: "MP D",
  },
  {
    name: "Delgado Vanesa",
    matrícula: 2395,
    fecha_matricula: "09/03",
    destino_matricula: "Banco F",
    marzo: 47497639980,
    fecha_marzo: "31/03",
    destino_marzo: "Banco F",
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Di Donato Silvina María Elda",
    matrícula: "V50P31",
    fecha_matricula: "22/02",
    destino_matricula: "MP F",
    marzo: "76V4MR22X7",
    fecha_marzo: "16/03",
    destino_marzo: "MP F",
    abril: 799218,
    fecha_abril: "10/04",
    destino_abril: "Banco D",
    mayo: 305508,
    fecha_mayo: "09/05",
    destino_mayo: "Banco D",
    junio: 735271,
    fecha_junio: "08/06",
    destino_junio: "Banco D",
    julio: "Bna+",
    fecha_julio: "07/07",
    destino_julio: "MP D",
  },
  {
    name: "Epinal Maria Laura",
    matrícula: 27842825,
    fecha_matricula: "15/02",
    destino_matricula: "Banco F",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Disser Milagros ",
    matrícula: "RECURSA",
    fecha_matricula: null,
    destino_matricula: null,
    marzo: "RECURSA",
    fecha_marzo: null,
    destino_marzo: null,
    abril: "RECURSA",
    fecha_abril: null,
    destino_abril: null,
    mayo: "RECURSA",
    fecha_mayo: null,
    destino_mayo: null,
    junio: "RECURSA",
    fecha_junio: null,
    destino_junio: null,
    julio: "RECURSA",
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Espindola Florencia Araceli",
    matrícula: 52117341552,
    fecha_matricula: null,
    destino_matricula: null,
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Escalante Melani",
    matrícula: 552800238330,
    fecha_matricula: "2/3",
    destino_matricula: "MP D",
    marzo: 55870998041,
    fecha_marzo: "18/03",
    destino_marzo: "MP D",
    abril: 56781917401,
    fecha_abril: "12/04",
    destino_abril: "MP D",
    mayo: "AFD963",
    fecha_mayo: "09/05",
    destino_mayo: "Banco D",
    junio: 5922483125,
    fecha_junio: "12/06",
    destino_junio: "MP D",
    julio: 60582383651,
    fecha_julio: "14/07",
    destino_julio: "MP D",
  },
  {
    name: "Ferrari Florencia ",
    matrícula: "50717473503 - 54778767495",
    fecha_matricula: "- / 16-02",
    destino_matricula: "MP / MP F",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Figueredo Clara",
    matrícula: 2575,
    fecha_matricula: "03/03",
    destino_matricula: "Banco D",
    marzo: 27783111,
    fecha_marzo: "10/03",
    destino_marzo: "Banco D",
    abril: 8019,
    fecha_abril: "10/04",
    destino_abril: "Banco D",
    mayo: 3049,
    fecha_mayo: "08/05",
    destino_mayo: "Banco D",
    junio: 2929,
    fecha_junio: "06/06",
    destino_junio: "Banco D",
    julio: 60341702044,
    fecha_julio: "06/07",
    destino_julio: "MP D",
  },
  {
    name: "Frias Yesica Roxana",
    matrícula: "52548782435 - 0",
    fecha_matricula: "- / 22-02",
    destino_matricula: "- / MP",
    marzo: "-",
    fecha_marzo: "10/03",
    destino_marzo: "MP",
    abril: 56918637076,
    fecha_abril: "14/04",
    destino_abril: "MP D",
    mayo: 58089393867,
    fecha_mayo: "15/05",
    destino_mayo: "MP D",
    junio: 59248909635,
    fecha_junio: "12/06",
    destino_junio: "MP D",
    julio: 60532203181,
    fecha_julio: "12/07",
    destino_julio: "MP D",
  },
  {
    name: "Garcia Florencia",
    matrícula: 55770027195,
    fecha_matricula: "15/03",
    destino_matricula: "Banco D",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Garrote Ines",
    matrícula: 941186,
    fecha_matricula: "2/3",
    destino_matricula: "Banco F",
    marzo: 326084,
    fecha_marzo: "17/03",
    destino_marzo: "Banco D",
    abril: 326084,
    fecha_abril: "17/03",
    destino_abril: "Banco D",
    mayo: 326084,
    fecha_mayo: "17/03",
    destino_mayo: "Banco D",
    junio: 326084,
    fecha_junio: "17/03",
    destino_junio: "Banco D",
    julio: 326084,
    fecha_julio: "17/03",
    destino_julio: "Banco D",
  },
  {
    name: "Giménez Elisa Beatriz",
    matrícula: 289072899,
    fecha_matricula: "06/03",
    destino_matricula: "MP D",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: 293889815,
    fecha_abril: "08/04",
    destino_abril: "Facu MP",
    mayo: 298754660,
    fecha_mayo: "09/05",
    destino_mayo: "Banco D",
    junio: 303242681,
    fecha_junio: "08/06",
    destino_junio: "Banco D",
    julio: 307058378,
    fecha_julio: "05/07",
    destino_julio: "Banco Sonia",
  },
  {
    name: "Geringer Carolina",
    matrícula: 962379,
    fecha_matricula: "01/03",
    destino_matricula: "Banco F",
    marzo: 962379,
    fecha_marzo: "01/03",
    destino_marzo: "Banco F",
    abril: 196699,
    fecha_abril: "26/04",
    destino_abril: "Banco F",
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Gonzalez Brisa Stephanie",
    matrícula: 54003327605,
    fecha_matricula: null,
    destino_matricula: null,
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Gonzo Aneli",
    matrícula: 8107,
    fecha_matricula: "2/3",
    destino_matricula: "Banco D",
    marzo: 9147,
    fecha_marzo: "09/03",
    destino_marzo: "Banco D",
    abril: 941,
    fecha_abril: "01/04",
    destino_abril: "Banco D",
    mayo: 8040,
    fecha_mayo: "05/05",
    destino_mayo: "Banco D",
    junio: 1111,
    fecha_junio: "02/06",
    destino_junio: "BANCO",
    julio: 43223656,
    fecha_julio: "05/07",
    destino_julio: "MP D",
  },
  {
    name: "Hertel Antonela Maricel",
    matrícula: "-",
    fecha_matricula: "16/02",
    destino_matricula: "MP F",
    marzo: "RD06ZO9W5",
    fecha_marzo: "16/03",
    destino_marzo: "MP F",
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Hood Jennifer ",
    matrícula: 95400218,
    fecha_matricula: "-",
    destino_matricula: "-",
    marzo: ".",
    fecha_marzo: "15/03",
    destino_marzo: "Banco D",
    abril: 44251570,
    fecha_abril: "18/04",
    destino_abril: "Banco D",
    mayo: "60169683 + 60413723",
    fecha_mayo: "22/05",
    destino_mayo: "Banco D",
    junio: 6774255,
    fecha_junio: "07/06",
    destino_junio: "Banco D",
    julio: 74165413,
    fecha_julio: "21/06",
    destino_julio: "MP D",
  },
  {
    name: "Jimenez De Navarro Mercedes",
    matrícula: 50160370019230310,
    fecha_matricula: "15/03",
    destino_matricula: "Banco D",
    marzo: 50160370019230310,
    fecha_marzo: "15/03",
    destino_marzo: "Banco D",
    abril: 50665785021230410,
    fecha_abril: "10/04",
    destino_abril: "Banco D",
    mayo: 11145434020230512,
    fecha_mayo: "12/05",
    destino_mayo: "Banco D",
    junio: 50134576020230610,
    fecha_junio: "08/06",
    destino_junio: "Banco D",
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Klubus Vanesa ",
    matrícula: 55282779448,
    fecha_matricula: "2/3",
    destino_matricula: "MP D",
    marzo: 55734956886,
    fecha_marzo: "14/03",
    destino_marzo: "MP D",
    abril: 56875063501,
    fecha_abril: "14/04",
    destino_abril: "MP D",
    mayo: 57718099960,
    fecha_mayo: "05/05",
    destino_mayo: "MP D",
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: 59608899859,
    fecha_julio: "21/06",
    destino_julio: "MP D",
  },
  {
    name: "Leiva Germán Alberto",
    matrícula: "51368930736 / 52344049818 / 54727267361",
    fecha_matricula: "- / 14/02",
    destino_matricula: "MP",
    marzo: "54727267361 -55448851249 ",
    fecha_marzo: "14/02/2023 - 07/03",
    destino_marzo: "MP",
    abril: 56770332012,
    fecha_abril: "10/04",
    destino_abril: "MP D",
    mayo: 57956271254,
    fecha_mayo: "10/05",
    destino_mayo: "MP D",
    junio: 59067317903,
    fecha_junio: "08/06",
    destino_junio: "MP D",
    julio: 60352087499,
    fecha_julio: "08/07",
    destino_julio: "MP D",
  },
  {
    name: "Lemos Lucía",
    matrícula: "-",
    fecha_matricula: "24/02",
    destino_matricula: "Banco D",
    marzo: "-",
    fecha_marzo: "10/03",
    destino_marzo: "Banco D",
    abril: 240612,
    fecha_abril: "30/04",
    destino_abril: "Banco D",
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Losada Natalia Fernanda ",
    matrícula: null,
    fecha_matricula: null,
    destino_matricula: null,
    marzo: "? - 19/07",
    fecha_marzo: "?",
    destino_marzo: "MP D",
    abril: 56814866852,
    fecha_abril: "11/04",
    destino_abril: "MP D",
    mayo: "Cuenta Dni",
    fecha_mayo: "14/05",
    destino_mayo: "MP D",
    junio: 59463032730,
    fecha_junio: "15/06",
    destino_junio: "MP D",
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Lucero Fabiana ",
    matrícula: 55281211275,
    fecha_matricula: "2/3",
    destino_matricula: "MP D",
    marzo: 56335473797,
    fecha_marzo: "31/03",
    destino_marzo: "MP D",
    abril: 56744834092,
    fecha_abril: "10/04",
    destino_abril: "MP D",
    mayo: 59141074318,
    fecha_mayo: "08/06",
    destino_mayo: "MP D",
    junio: 59142940952,
    fecha_junio: "08/06",
    destino_junio: "MP D",
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "López, Juan Ezequiel ",
    matrícula: "25846030455 - 55442055910",
    fecha_matricula: "- / 6-03",
    destino_matricula: "- / MP D",
    marzo: 56246389693,
    fecha_marzo: "29/03",
    destino_marzo: "MP D",
    abril: 56875689618,
    fecha_abril: "13/04",
    destino_abril: "MP D",
    mayo: 58517021260,
    fecha_mayo: "24/05",
    destino_mayo: "MP D",
    junio: 59941820604,
    fecha_junio: "27/06",
    destino_junio: "MP D",
    julio: 60730717411,
    fecha_julio: "16/07",
    destino_julio: "MP D",
  },
  {
    name: "Machado Rosa Eduarda",
    matrícula: "8D0Q619L5533Q0X27JZ5RG",
    fecha_matricula: "15/02",
    destino_matricula: "Banco F",
    marzo: "LOEJWV9JWLPXGZM2QMD0GZ",
    fecha_marzo: "15/03",
    destino_marzo: "Banco D",
    abril: "8D0Q619LGO5PRKL27JZ5RG",
    fecha_abril: "19/04",
    destino_abril: "Banco D",
    mayo: "Z6OLMDN3LKQMD8X9E7RQ5X",
    fecha_mayo: "15/05",
    destino_mayo: "Banco D",
    junio: 59413650864,
    fecha_junio: "14/06",
    destino_junio: "MP D",
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Mallo Santana Agustina Belen",
    matrícula: 55575137917,
    fecha_matricula: "10/03",
    destino_matricula: "MP F",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Mallo Estefanía ",
    matrícula: 55575137917,
    fecha_matricula: "09/03",
    destino_matricula: "MP F",
    marzo: 56381926198,
    fecha_marzo: "31/03",
    destino_marzo: "MP F",
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Mardones Raquel",
    matrícula: 55245020214,
    fecha_matricula: "1/3",
    destino_matricula: "MP D",
    marzo: 55613961610,
    fecha_marzo: "10/03",
    destino_marzo: "MP D",
    abril: 65687977101,
    fecha_abril: "06/04",
    destino_abril: "MP D",
    mayo: 57836926481,
    fecha_mayo: "09/05",
    destino_mayo: "MP D",
    junio: 59128997275,
    fecha_junio: "09/06",
    destino_junio: "MP D",
    julio: 60422149868,
    fecha_julio: "07/07",
    destino_julio: "MP D",
  },
  {
    name: "Margaria Lorena",
    matrícula: "28/12 13:38hs",
    fecha_matricula: "-",
    destino_matricula: "-",
    marzo: "Z4K6DVNO5W",
    fecha_marzo: "16/03",
    destino_marzo: "MP",
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "MELO NUÑEZ FABIOLA ",
    matrícula: 24310615579,
    fecha_matricula: "-",
    destino_matricula: "-",
    marzo: 26490647271,
    fecha_marzo: "14/03",
    destino_marzo: "MP D",
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Miksa Paula Pilar",
    matrícula: "52836700774 - 280411",
    fecha_matricula: "- / 24-02",
    destino_matricula: "- / Banco Daniel",
    marzo: 280411,
    fecha_marzo: "24-02",
    destino_marzo: "Banco D",
    abril: 56820166877,
    fecha_abril: "13/04",
    destino_abril: "MP D",
    mayo: 58165282949,
    fecha_mayo: "17/05",
    destino_mayo: "MP D",
    junio: 58790606657,
    fecha_junio: "02/06",
    destino_junio: "MP D",
    julio: 60245346173,
    fecha_julio: "06/07",
    destino_julio: "MP D",
  },
  {
    name: "Miranda Veronica Andrea",
    matrícula: 55253419414,
    fecha_matricula: "1/3",
    destino_matricula: "MP F",
    marzo: 55816750508,
    fecha_marzo: "16/03",
    destino_marzo: "MP D",
    abril: 56391951880,
    fecha_abril: "01/04",
    destino_abril: "MP D",
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Montenegro Mirta",
    matrícula: null,
    fecha_matricula: null,
    destino_matricula: null,
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Moyano Debora  ",
    matrícula: "7F5746",
    fecha_matricula: null,
    destino_matricula: null,
    marzo: "7006BD",
    fecha_marzo: "11/03",
    destino_marzo: "Banco S",
    abril: 56817069331,
    fecha_abril: "12/04",
    destino_abril: "MP D",
    mayo: 58698648323,
    fecha_mayo: "31/05",
    destino_mayo: "MP D",
    junio: 59435765193,
    fecha_junio: "16/06",
    destino_junio: "MP D",
    julio: 60783415865,
    fecha_julio: "17/07",
    destino_julio: "MP D",
  },
  {
    name: "Moyano Maria Esther",
    matrícula: "-",
    fecha_matricula: "2/3",
    destino_matricula: "MP D",
    marzo: "-",
    fecha_marzo: "16/03",
    destino_marzo: "MP D",
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Moyano Silvana",
    matrícula: 55358888970,
    fecha_matricula: "4/3",
    destino_matricula: "MP D",
    marzo: 56015634383,
    fecha_marzo: "22/03",
    destino_marzo: "MP D",
    abril: 56555144848,
    fecha_abril: "05/04",
    destino_abril: "MP D",
    mayo: 59146770432,
    fecha_mayo: "08/06",
    destino_mayo: "MP D",
    junio: 59360628263,
    fecha_junio: "15/06",
    destino_junio: "MP D",
    julio: 61211610584,
    fecha_julio: "25/07",
    destino_julio: "MP D",
  },
  {
    name: "Ponteprimo Ana Laura",
    matrícula: "-",
    fecha_matricula: "01/03",
    destino_matricula: "MP D",
    marzo: "-",
    fecha_marzo: "01/03",
    destino_marzo: "MP D",
    abril: 59803211502,
    fecha_abril: "23/06",
    destino_abril: "MP D",
    mayo: 59803211502,
    fecha_mayo: "23/06",
    destino_mayo: "MP D",
    junio: 59803211502,
    fecha_junio: "23/06",
    destino_junio: "MP D",
    julio: 55,
    fecha_julio: "06/07",
    destino_julio: "MP D",
  },
  {
    name: "Pintos Agustina Ailén",
    matrícula: 55279505862,
    fecha_matricula: "2/3",
    destino_matricula: "MP D",
    marzo: 55590630807,
    fecha_marzo: "10/03",
    destino_marzo: "MP D",
    abril: 56961479776,
    fecha_abril: "15/04",
    destino_abril: "MP D",
    mayo: 58137750552,
    fecha_mayo: "14/05",
    destino_mayo: "MP D",
    junio: 59456737130,
    fecha_junio: "15/06",
    destino_junio: "MP D",
    julio: "Cuenta Dni",
    fecha_julio: "14/07",
    destino_julio: "MP D",
  },
  {
    name: "Pundan Joaquin",
    matrícula: 52263516057,
    fecha_matricula: null,
    destino_matricula: null,
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "QUIROZ Ester Noemi",
    matrícula: "-",
    fecha_matricula: "17/03",
    destino_matricula: "MP",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Reyes Liliana",
    matrícula: 55338601024,
    fecha_matricula: "03/03",
    destino_matricula: "MP D",
    marzo: 55560111093,
    fecha_marzo: "09/03",
    destino_marzo: "MP D",
    abril: 56622839223,
    fecha_abril: "07/04",
    destino_abril: "MP D",
    mayo: 56627198,
    fecha_mayo: "13/05",
    destino_mayo: "Banco D",
    junio: 58776216389,
    fecha_junio: "01/06",
    destino_junio: "MP D",
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Rios Garcia Mariana Zulma",
    matrícula: 55348710544,
    fecha_matricula: "04/03",
    destino_matricula: "MP D",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Ripoll Yanina",
    matrícula: 890786,
    fecha_matricula: "2/3",
    destino_matricula: "Banco D",
    marzo: "-",
    fecha_marzo: "12/04",
    destino_marzo: "?",
    abril: "-",
    fecha_abril: "16/05",
    destino_abril: "MP D",
    mayo: "-",
    fecha_mayo: "05/06",
    destino_mayo: "MP D",
    junio: "-",
    fecha_junio: "2/07/2023 11:42hs",
    destino_junio: "MP D",
    julio: "-",
    fecha_julio: "2/07/2023 11:42hs",
    destino_julio: "MP D",
  },
  {
    name: "Rivero Mailen",
    matrícula: "54300111382 / 54300166456  03/02 MP",
    fecha_matricula: null,
    destino_matricula: "MP F",
    marzo: 55612224413,
    fecha_marzo: "11/03",
    destino_marzo: "MP D",
    abril: 56742425322,
    fecha_abril: "10/04",
    destino_abril: "MP F",
    mayo: 58726870626,
    fecha_mayo: "30/05",
    destino_mayo: "MP D",
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Rodríguez Marcela",
    matrícula: 64202991,
    fecha_matricula: null,
    destino_matricula: "Banco",
    marzo: 26212743,
    fecha_marzo: "08/03",
    destino_marzo: "Banco",
    abril: 37212290,
    fecha_abril: "04/04",
    destino_abril: "Banco",
    mayo: 50485219,
    fecha_mayo: "03/05",
    destino_mayo: "Banco D",
    junio: 66164709,
    fecha_junio: "05/06",
    destino_junio: "Banco D",
    julio: 81387512,
    fecha_julio: "05/07",
    destino_julio: "Banco D",
  },
  {
    name: "Rodríguez Romina Isabel ",
    matrícula: 55862359394,
    fecha_matricula: "17/03",
    destino_matricula: "MP D",
    marzo: 55862359394,
    fecha_marzo: "17/03",
    destino_marzo: "MP D",
    abril: 57135974874,
    fecha_abril: "20/04",
    destino_abril: "MP D",
    mayo: 58151172558,
    fecha_mayo: "15/05",
    destino_mayo: "MP D",
    junio: 59310737109,
    fecha_junio: "14/06",
    destino_junio: "MP D",
    julio: 60617171417,
    fecha_julio: "14/07",
    destino_julio: "MP D",
  },
  {
    name: "Romero Maria Soledad",
    matrícula: "51404643593 - 55075441722",
    fecha_matricula: "- / 24-02",
    destino_matricula: "- / MP D",
    marzo: 55455289587,
    fecha_marzo: "07/03",
    destino_marzo: "MP D",
    abril: 56712612993,
    fecha_abril: "10/04",
    destino_abril: "MP D",
    mayo: 57996491822,
    fecha_mayo: "11/05",
    destino_mayo: "MP D",
    junio: 59316173102,
    fecha_junio: "12/06",
    destino_junio: "MP D",
    julio: 60753924612,
    fecha_julio: "14/07",
    destino_julio: "MP D",
  },
  {
    name: "Salinas Medina Silvia Elizabeth",
    matrícula: 461371,
    fecha_matricula: "24/02",
    destino_matricula: "MP F",
    marzo: "-",
    fecha_marzo: "16/03",
    destino_marzo: "MP ",
    abril: "-",
    fecha_abril: "08/04",
    destino_abril: "MP",
    mayo: "Cuenta Dni",
    fecha_mayo: "07/05",
    destino_mayo: "MP D",
    junio: "Cuenta Dni",
    fecha_junio: "08/06",
    destino_junio: "MP D",
    julio: "Cuenta Dni",
    fecha_julio: "10/07",
    destino_julio: "MP D",
  },
  {
    name: "Sosa Araceli Evelin",
    matrícula: 55291177034,
    fecha_matricula: "2/3",
    destino_matricula: "Banco D",
    marzo: 56208562605,
    fecha_marzo: "28/03",
    destino_marzo: "MP D",
    abril: 56208562605,
    fecha_abril: "28/03",
    destino_abril: "MP D",
    mayo: 59076161232,
    fecha_mayo: "06/06",
    destino_mayo: "MP D",
    junio: 60645820327,
    fecha_junio: "14/07",
    destino_junio: "MP D",
    julio: 60645820327,
    fecha_julio: "14/07",
    destino_julio: "MP D",
  },
  {
    name: "Staltari Patricia ",
    matrícula: 55563437076,
    fecha_matricula: "09/03",
    destino_matricula: "MP F",
    marzo: 55840204424,
    fecha_marzo: "16/03",
    destino_marzo: "MP F",
    abril: 56593560910,
    fecha_abril: "06/04",
    destino_abril: "MP F",
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Suarez Silvia Beatriz",
    matrícula: 55295048594,
    fecha_matricula: "2/3",
    destino_matricula: "MP D",
    marzo: 55616755807,
    fecha_marzo: "11/03",
    destino_marzo: "MP D",
    abril: 57019940658,
    fecha_abril: "17/04",
    destino_abril: "MP D",
    mayo: "58430826484 + 58359032457",
    fecha_mayo: "22/05",
    destino_mayo: "MP D",
    junio: 59397273074,
    fecha_junio: "14/06",
    destino_junio: "MP D",
    julio: 60632543644,
    fecha_julio: "12/07",
    destino_julio: "MP D",
  },
  {
    name: "Tejerina Liliana Del Valle ",
    matrícula: "1903 / -",
    fecha_matricula: "- / 1-3",
    destino_matricula: "Banco",
    marzo: 10886450,
    fecha_marzo: "3/4",
    destino_marzo: "MP",
    abril: 10886450,
    fecha_abril: "3/4",
    destino_abril: "MP",
    mayo: 10884252,
    fecha_mayo: "12/06",
    destino_mayo: "MP ",
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Uribe Durand Priscila Tatiana ",
    matrícula: 50428957916,
    fecha_matricula: null,
    destino_matricula: null,
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Tormo Monica Adriana",
    matrícula: 117616,
    fecha_matricula: "17/02",
    destino_matricula: "MP F",
    marzo: 337518,
    fecha_marzo: "06/03",
    destino_marzo: "MP F",
    abril: 193735,
    fecha_abril: "06/04",
    destino_abril: "Facu",
    mayo: 767297,
    fecha_mayo: "04/05",
    destino_mayo: "Banco D",
    junio: 733246,
    fecha_junio: "05/06",
    destino_junio: "Banco D",
    julio: 443895,
    fecha_julio: "04/07",
    destino_julio: "Banco D",
  },
  {
    name: "Torres Laura Karina",
    matrícula: "22/12 10:54hs",
    fecha_matricula: null,
    destino_matricula: null,
    marzo: "-",
    fecha_marzo: "16/03",
    destino_marzo: "MP",
    abril: 361739,
    fecha_abril: "10/04",
    destino_abril: "Banco D",
    mayo: "-",
    fecha_mayo: "10/05",
    destino_mayo: "Banco D",
    junio: 36371,
    fecha_junio: "09/06",
    destino_junio: "Banco D",
    julio: "Bna+",
    fecha_julio: "12/07",
    destino_julio: "MP D",
  },
  {
    name: "Turco Romina",
    matrícula: 55305149489,
    fecha_matricula: "03/03",
    destino_matricula: "MP D",
    marzo: 55810203181,
    fecha_marzo: "16/03",
    destino_marzo: "MP D",
    abril: 56560874439,
    fecha_abril: "06/04",
    destino_abril: "MP D",
    mayo: 57894454614,
    fecha_mayo: "09/05",
    destino_mayo: "MP D",
    junio: 59069350229,
    fecha_junio: "08/06",
    destino_junio: "MP D",
    julio: 60393262318,
    fecha_julio: "07/07",
    destino_julio: "MP D",
  },
  {
    name: "Vargas Escalante Isaias Augusto",
    matrícula: "1903 / -",
    fecha_matricula: "- / 1-3",
    destino_matricula: "Banco",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Vega María Alcira",
    matrícula: "- / - / -",
    fecha_matricula: " 06/01 10:24hs - 15/02 - 07/03",
    destino_matricula: "MP Facu",
    marzo: "-",
    fecha_marzo: "07/03",
    destino_marzo: "MP",
    abril: "Rapipago",
    fecha_abril: "12/05",
    destino_abril: "MP",
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: "Rapipago ",
    fecha_junio: "08/06",
    destino_junio: "MP",
    julio: "Rapipago",
    fecha_julio: "06/07",
    destino_julio: "MP",
  },
  {
    name: "Velazquez Juan Antonio",
    matrícula: 51988238059,
    fecha_matricula: null,
    destino_matricula: null,
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Condori Carla Mariel",
    matrícula: "10/01 12:47hs",
    fecha_matricula: null,
    destino_matricula: null,
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Avalos Melanie Julieta",
    matrícula: 54520293727,
    fecha_matricula: "09/02",
    destino_matricula: "MP F",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Yucra Luis Miguel",
    matrícula: "V50P32",
    fecha_matricula: "23/02",
    destino_matricula: "MP F",
    marzo: "V50P32",
    fecha_marzo: "23/02",
    destino_marzo: "MP F",
    abril: 56745903945,
    fecha_abril: "11/04",
    destino_abril: "MP D",
    mayo: 58106635870,
    fecha_mayo: "13/05",
    destino_mayo: "MP D",
    junio: 59116868635,
    fecha_junio: "09/06",
    destino_junio: "MP D",
    julio: 60185161729,
    fecha_julio: "05/07",
    destino_julio: "MP D",
  },
  {
    name: "Zacarías Celeste",
    matrícula: 23273337,
    fecha_matricula: "2/3",
    destino_matricula: "Banco D",
    marzo: 23273337,
    fecha_marzo: "2/3",
    destino_marzo: "Banco D",
    abril: 40502206,
    fecha_abril: "10/04",
    destino_abril: "Banco D",
    mayo: 40502206,
    fecha_mayo: "10/04",
    destino_mayo: "Banco D",
    junio: 68308205,
    fecha_junio: "08/06",
    destino_junio: "Banco D",
    julio: 68308205,
    fecha_julio: "08/06",
    destino_julio: "Banco D",
  },
  {
    name: "Alfredo ",
    matrícula: 2780,
    fecha_matricula: "15/02",
    destino_matricula: "Banco F",
    marzo: 2780,
    fecha_marzo: "15/02",
    destino_marzo: "Banco F",
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Balent Santiago Román ",
    matrícula: 55296415769,
    fecha_matricula: "03/03",
    destino_matricula: "MP D",
    marzo: null,
    fecha_marzo: null,
    destino_marzo: null,
    abril: null,
    fecha_abril: null,
    destino_abril: null,
    mayo: null,
    fecha_mayo: null,
    destino_mayo: null,
    junio: null,
    fecha_junio: null,
    destino_junio: null,
    julio: null,
    fecha_julio: null,
    destino_julio: null,
  },
  {
    name: "Aranciaga Lara",
    matrícula: "Cuenta Dni",
    fecha_matricula: "13/04",
    destino_matricula: "MP D",
    marzo: "Cuenta Dni",
    fecha_marzo: "13/04",
    destino_marzo: "MP D",
    abril: "Cuenta Dni",
    fecha_abril: "20/04",
    destino_abril: "MP D",
    mayo: "243054 + 621421",
    fecha_mayo: "20/05",
    destino_mayo: "Banco D",
    junio: "392274 - 112039",
    fecha_junio: "19/06",
    destino_junio: "Banco D",
    julio: 60997983577,
    fecha_julio: "22/07",
    destino_julio: "MP D",
  },
];
function unirArrays(valores, comprobante) {
  const resultado = [];

  for (let i = 0; i < valores.length; i++) {
    const valor = valores[i];
    const comp = comprobante[i];

    for (const key in valor) {
      if (key !== "name" && valor[key] != null && valor[key] !== "") {
        const concept = key;
        const amount = typeof valor[key] === "number" ? valor[key] : parseFloat(valor[key]);

        // Extract the payday based on the "fecha_{concept}" format
        const paydayKey = `fecha_${concept}`;
        const payday = comp[paydayKey] ? comp[paydayKey].trim() : "";

        const receipt = typeof comp[key] === "number" ? comp[key].toString() : "";

        resultado.push({
          name: valor.name,
          concept,
          amount: typeof amount === "number" ? amount : parseFloat(amount),
          payday,
          receipt,
        });
      }
    }
  }

  return resultado;
}

console.log(unirArrays(valores, comprobantes));

